PROG = digit_generator
OBJ = 
CFLAGS = -g -Wall -o2
LDLIBS = 
OUTPUT = ../exe
EXE = $(PROG).exe
CC = c99



$(PROG):$(OBJ);

#mv $(EXE) $(OUTPUT)
.PHONY :clean
clean:	
	# vi cache
	@rm -f *~
	@rm -f .*~
