PROG = digit_generator
OBJ = 
CFLAGS = -g -Wall -o2
LDLIBS = 
OUTPUT = ../exe
EXE = $(PROG).exe
CC = c99

build: $(EXE)
	mv $(EXE) $(OUTPUT)
$(PROG):$(OBJ)

.PHONY :clean
clean:	
	# vi cache
	@rm -f *~
	@rm -f .*~
