PROG = na
OBJ = 
CFLAGS = -g -Wall -o2
LDLIBS = 
OUTPUT = ../exe
EXE = $(PROG).exe
CC = c99
EXE_PATH = ../exe


$(PROG):$(OBJ)


.PHONY :clean
clean:
	# vi cache
	@rm -f *~
	@rm -f .*~
	@rm -f *.exe
move:
	@mv $(EXE) $(EXE_PATH)
